### PR TITLE
Notes fixups

### PR DESCRIPTION
**Pull request by marktriggs**

### CODE REVIEW

**Comment by marktriggs** [comment]
I've given it some thought and I think this PR is very good and should be merged. :+1:

**Comment by jambun** [comment]
Have you actually tested it? 🙁

**Comment by jambun** [comment]
Got any more force pushes up your sleeve?

**Comment by marktriggs** [comment]
YES

James Bullen <notifications@github.com> writes:

> Have you actually tested it? 🙁 

-- 
Mark Triggs
<mark@dishevelled.net>

**Comment by jambun** [comment]
Ok, awlright.  🥇

**Pull request merged**
